# Generated by Django 5.2 on 2025-06-28 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Casedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=100)),
                ('case_description', models.CharField(max_length=1000)),
                ('case_image', models.ImageField(blank=True, null=True, upload_to='caseimg/')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('anydoc', models.ImageField(blank=True, null=True, upload_to='document/')),
                ('case_type', models.CharField(choices=[('tax', 'TAX'), ('divorse', 'DIVORSE'), ('criminal', 'CRIMINAL'), ('civil', 'CIVIL'), ('family', 'FAMILY'), ('environmental', 'ENVIRONMENTAL'), ('bankruptcy', 'BANKRUPTY'), ('cild abuse', 'CHILD ABUSE'), ('constitutional', 'CONSTITUTIONAL'), ('administrative', 'ADMINISTRATIVE'), ('contract', 'CONTRACT'), ('tort', 'TORT'), ('property', 'PROPERTY'), ('intellectual property', 'INTELLECTUAL PROPERTY'), ('probate', 'PROBATE')], default='Tax Law', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyerdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('yearofexperience', models.IntegerField()),
                ('specialization', models.CharField(max_length=100)),
                ('totalcases', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lawyerimg/')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('case_type', models.CharField(choices=[('tax', 'TAX'), ('divorse', 'DIVORSE'), ('criminal', 'CRIMINAL'), ('civil', 'CIVIL'), ('family', 'FAMILY'), ('environmental', 'ENVIRONMENTAL'), ('bankruptcy', 'BANKRUPTY'), ('cild abuse', 'CHILD ABUSE'), ('constitutional', 'CONSTITUTIONAL'), ('administrative', 'ADMINISTRATIVE'), ('contract', 'CONTRACT'), ('tort', 'TORT'), ('property', 'PROPERTY'), ('intellectual property', 'INTELLECTUAL PROPERTY'), ('probate', 'PROBATE')], default='tax', max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('casedoc', models.ImageField(blank=True, null=True, upload_to='appointmentimg/')),
                ('total_no_of_hearing', models.IntegerField()),
                ('court_name', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Case_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='lawfirmapp.appointment')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyerdetail', to='lawfirmapp.lawyerdetails')),
            ],
        ),
    ]
